Latest

diff --git a/home/dot_local/bin/executable_install-terminal-theme.tmpl b/home/dot_local/bin/executable_install-terminal-theme.tmpl
--- a/home/dot_local/bin/executable_install-terminal-theme.tmpl
+++ b/home/dot_local/bin/executable_install-terminal-theme.tmpl
@@ -40,8 +40,9 @@ export PROFILE_NAME="Betelgeuse"
 if [ ! -e gconftool-2 ] && [ -f /etc/debian_version ]; then
   logg 'Running sudo apt-get update'
   sudo apt-get update
-  logg 'Running sudo apt-get install -y gconf2'
-  sudo apt-get install -y gconf2
+  logg 'Running sudo apt-get install -y gconf2 || true'
+  logg 'This may only be required on older versions of OSes that use apt-get'
+  sudo apt-get install -y gconf2 || true
 fi
 
 # |
