Update .local/share/chezmoi/home/.chezmoiscripts/universal/run_onchange_before_91-configure-gpg.tmpl, .local/share/chezmoi/home/.chezmoiscripts/universal/run_once_before_decrypt-age-key.tmpl

diff --git a/.local/share/chezmoi/home/.chezmoiscripts/universal/run_onchange_before_91-configure-gpg.tmpl b/.local/share/chezmoi/home/.chezmoiscripts/universal/run_onchange_before_91-configure-gpg.tmpl
--- a/.local/share/chezmoi/home/.chezmoiscripts/universal/run_onchange_before_91-configure-gpg.tmpl
+++ b/.local/share/chezmoi/home/.chezmoiscripts/universal/run_onchange_before_91-configure-gpg.tmpl
@@ -20,7 +20,14 @@ if [ -n "$KEYID" ] && command -v gpg > /dev/null; then
   KEYID_TRIMMED="$(echo "$KEYID" | sed 's/^0x//')"
   if ! gpg --list-secret-keys --keyid-format=long | grep "$KEYID_TRIMMED" > /dev/null; then
     logg info 'Attempting to download the specified public GPG key (`{{ .user.gpg.id }}`) from public keyservers'
-    gpg --recv "$KEYID"
+    gpg --recv "$KEYID" || EXIT_CODE=$?
+    if [ -n "$EXIT_CODE" ]; then
+      logg warn 'Error downloading public GPG key'
+      logg info 'Retrying after turning on debug mode and using the standard DNS resolver'
+      sudo pkill dirmngr
+      dirmngr --debug-all --daemon --standard-resolver
+      gpg --recv "$KEYID"
+    fi
   else
     logg info 'Key is already in keyring'
   fi
