Latest

diff --git a/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl b/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl
--- a/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl
+++ b/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl
@@ -164,13 +164,11 @@ upgradeDarwin() {
       fi
 
       ### Reboot
-      logg info 'Reboot required'
-      logg info 'Attempting to restart gracefully'
-      gtimeout 60 osascript -e 'tell application "Finder" to shut down' || OSASCRIPT_EXIT_CODE=$?
-      if [ -n "$OSASCRIPT_EXIT_CODE" ]; then
-        logg info 'Reboot required and failed to gracefully shutdown within 1 minute, so forcing reboot' && sudo sh -c 'shutdown -r now'
-      fi
-      exit 0
+      logg info 'Reboot required' && exit 140
+      # gtimeout 60 osascript -e 'tell application "Finder" to shut down' || OSASCRIPT_EXIT_CODE=$?
+      # if [ -n "$OSASCRIPT_EXIT_CODE" ]; then
+      #   logg info 'Reboot required and failed to gracefully shutdown within 1 minute, so forcing reboot' && sudo sh -c 'shutdown -r now'
+      # fi
     else
       logg info 'No reboot required for softwareupdate'
     fi
diff --git a/scripts/src/provision.sh.tmpl b/scripts/src/provision.sh.tmpl
--- a/scripts/src/provision.sh.tmpl
+++ b/scripts/src/provision.sh.tmpl
@@ -326,31 +326,40 @@ runChezmoi() {
     logg info 'Running chezmoi apply forcefully'
     if command -v unbuffer > /dev/null; then
       if command -v caffeinate > /dev/null; then
-        caffeinate unbuffer -p chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE"
+        caffeinate unbuffer -p chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       else
-        unbuffer -p chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE"
+        unbuffer -p chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       fi
     else
       if command -v caffeinate > /dev/null; then
-        caffeinate chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE"
+        caffeinate chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       else
-        chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE"
+        chezmoi apply $DEBUG_MODIFIER -k --force 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       fi
     fi
   else
     logg info 'Running chezmoi apply'
     if command -v unbuffer > /dev/null; then
       if command -v caffeinate > /dev/null; then
-        caffeinate unbuffer -p chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE"
+        caffeinate unbuffer -p chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       else
-        unbuffer -p chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE"
+        unbuffer -p chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       fi    
     else
       if command -v caffeinate > /dev/null; then
-        caffeinate chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE"
+        caffeinate chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       else
-        chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE"
+        chezmoi apply $DEBUG_MODIFIER -k 2>&1 | tee "$LOG_FILE" || CHEZMOI_EXIT_CODE=$?
       fi    
+    fi
+  fi
+  if [ -n "$CHEZMOI_EXIT_CODE" ]; then
+    if [ "$CHEZMOI_EXIT_CODE" = "140" ]; then
+      logg info "Chezmoi signalled that a reboot is necessary to apply a system update"
+      logg info "Running softwareupdate with the reboot flag"
+      sudo softwareupdate -i -a -R --agree-to-license && exit
+    else
+      logg error "Chezmoi encountered an error and exitted with an exit code of $CHEZMOI_EXIT_CODE"
     fi
   fi
 }
