Update 2 files
- /home/.chezmoiscripts/universal/run_onchange_after_40-firefox.sh.tmpl
- /home/.chezmoiscripts/universal/run_onchange_before_14-warp.sh.tmpl

diff --git a/home/.chezmoiscripts/universal/run_onchange_before_14-warp.sh.tmpl b/home/.chezmoiscripts/universal/run_onchange_before_14-warp.sh.tmpl
--- a/home/.chezmoiscripts/universal/run_onchange_before_14-warp.sh.tmpl
+++ b/home/.chezmoiscripts/universal/run_onchange_before_14-warp.sh.tmpl
@@ -65,9 +65,15 @@ if [[ ! "$(test -d /proc && grep Microsoft /proc/version > /dev/null)" ]]; then
         sudo apt-get update && sudo apt-get install -y cloudflare-warp
     elif command -v dnf > /dev/null && command -v rpm > /dev/null; then
         ### This is made for CentOS 8 and works on Fedora 36 (hopefully 36+ as well) with `nss-tools` as a dependency
-        sudo dnf instal -y nss-tools
+        sudo dnf instal -y nss-tools || NSS_TOOL_EXIT=$?
+        if [ -n "$NSS_TOOL_EXIT" ]; then
+            logg warn 'Unable to install `nss-tools` which was a requirement on Fedora 36 and assumed to be one on other systems as well.'
+        fi
         ### According to the download site, this is the only version available for RedHat-based systems
-        sudo rpm -ivh https://pkg.cloudflareclient.com/cloudflare-release-el8.rpm
+        sudo rpm -ivh https://pkg.cloudflareclient.com/cloudflare-release-el8.rpm || RPM_EXIT_CODE=$?
+        if [ -n "$RPM_EXIT_CODE" ]; then
+            logg error 'Unable to install CloudFlare WARP using RedHat 8 RPM package'
+        fi
     fi
 fi
 
