Update to improved gum formatting

diff --git a/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl b/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl
--- a/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl
+++ b/home/.chezmoiscripts/universal/run_before_02-homebrew.sh.tmpl
@@ -77,13 +77,13 @@ ensurePackageManagerHomebrew() {
       echo | bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
       fixHomebrewPermissions
     else
-      logg info 'Homebrew is not installed. Password may be required.'
+      gum log -sl info 'Homebrew is not installed. Password may be required.'
       bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || BREW_EXIT_CODE="$?"
       fixHomebrewPermissions
       if [ -n "$BREW_EXIT_CODE" ]; then
-        logg warn 'Homebrew was installed but part of the installation failed to complete successfully.'
+        gum log -sl warn 'Homebrew was installed but part of the installation failed to complete successfully.'
         if command -v brew > /dev/null; then
-          logg info 'Applying proper permissions on Homebrew folders'
+          gum log -sl info 'Applying proper permissions on Homebrew folders'
           sudo chmod -R go-w "$(brew --prefix)/share"
           BREW_DIRS="share etc/bash_completion.d"
           for BREW_DIR in $BREW_DIRS; do
@@ -91,7 +91,7 @@ ensurePackageManagerHomebrew() {
               sudo chown -Rf "$(whoami)" "$(brew --prefix)/$BREW_DIR"
             fi
           done
-          logg info 'Running brew update --force --quiet' && brew update --force --quiet
+          gum log -sl info 'Running brew update --force --quiet' && brew update --force --quiet
         fi
       fi
     fi
@@ -101,21 +101,21 @@ ensurePackageManagerHomebrew() {
 # @description Helper function utilized by [[upgradeDarwin]] to ensure the `expect` command is available on macOS
 installExpect() {
   if ! command -v expect > /dev/null; then
-    logg info 'Installing expect via Homebrew' && brew install expect
+    gum log -sl info 'Installing expect via Homebrew' && brew install expect
   fi
 }
 
 # @description Helper function utilized by [[upgradeDarwin]] to ensure the `gsed` command is available on macOS
 installGsed() {
   if ! command -v gsed > /dev/null; then
-    logg info 'Installing gnu-sed via Homebrew' && brew install gnu-sed
+    gum log -sl info 'Installing gnu-sed via Homebrew' && brew install gnu-sed
   fi
 }
 
 # @description Helper function utilized by [[upgradeDarwin]] to ensure the `gtimeout` command is available on macOS
 installGtimeout() {
   if ! command -v gtimeout > /dev/null; then
-    logg info 'Installing coreutils via Homebrew' && brew install coreutils
+    gum log -sl info 'Installing coreutils via Homebrew' && brew install coreutils
   fi
 }
 
@@ -148,64 +148,64 @@ upgradeDarwin() {
 
     ### Ensure Rosetta 2 is installed
     if /usr/bin/pgrep -q oahd; then
-      logg info 'Rosetta 2 is already installed'
+      gum log -sl info 'Rosetta 2 is already installed'
     else
-      logg info 'Ensuring Rosetta 2 is installed' && softwareupdate --install-rosetta --agree-to-license
+      gum log -sl info 'Ensuring Rosetta 2 is installed' && softwareupdate --install-rosetta --agree-to-license
     fi
 
     ### Run upgrade process
-    logg info 'Checking for available OS upgrades'
+    gum log -sl info 'Checking for available OS upgrades'
     UPDATE_CHECK="$(softwareupdate -l 2>&1)"
     if ! echo "$UPDATE_CHECK" | grep "No new software available" > /dev/null; then
-      logg info 'There are available OS upgrades'
+      gum log -sl info 'There are available OS upgrades'
       echo "$UPDATE_CHECK"
-      logg info 'Applying OS upgrades (if available). This may take awhile..'
+      gum log -sl info 'Applying OS upgrades (if available). This may take awhile..'
       expect -c "set timeout -1
       spawn sudo softwareupdate -i -a --agree-to-license
       expect \"Password:\"
       send \"${SUDO_PASSWORD}\r\"
       expect eof" &> /dev/null || EXIT_CODE=$?
       if [ -n "$EXIT_CODE" ]; then
-        logg warn 'Error running softwareupdate'
+        gum log -sl warn 'Error running softwareupdate'
         unset EXIT_CODE
       fi
-      # sudo sh -c "sudo softwareupdate -i -a --agree-to-license" || logg error 'Failed to trigger a system update via sudo softwareupdate -i -a --agree-to-license'
+      # sudo sh -c "sudo softwareupdate -i -a --agree-to-license" || gum log -sl error 'Failed to trigger a system update via sudo softwareupdate -i -a --agree-to-license'
 
       ### Reboot if necessary
       # Source: https://community.jamf.com/t5/jamf-pro/determine-if-update-requires-restart/m-p/11682
-      logg info 'Checking if softwareupdate requires a reboot'
+      gum log -sl info 'Checking if softwareupdate requires a reboot'
       if softwareupdate -l | grep restart > /dev/null; then
         ### Add kickstart script to .zshrc so it triggers automatically
         if [ ! -f "$HOME/.zshrc" ] || ! cat "$HOME/.zshrc" | grep '# TEMPORARY FOR INSTALL DOCTOR MACOS' > /dev/null; then
-          logg info 'Adding kickstart script to ~/.zshrc so script continues automatically if reboot is necessary'
+          gum log -sl info 'Adding kickstart script to ~/.zshrc so script continues automatically if reboot is necessary'
           echo 'bash <(curl -sSL --compressed https://install.doctor/start) # TEMPORARY FOR INSTALL DOCTOR MACOS' >> "$HOME/.zshrc"
         fi
 
         if [ -n "$SUDO_PASSWORD" ] && [ "$SUDO_PASSWORD" != "" ]; then
           ### Install kcpassword
           if ! command -v enable_autologin > /dev/null; then
-            logg info 'enable_autologin is not installed and it is a requirement for auto-logging in after reboot' && brew install xfreebird/utils/kcpassword
+            gum log -sl info 'enable_autologin is not installed and it is a requirement for auto-logging in after reboot' && brew install xfreebird/utils/kcpassword
           fi
 
           ### Enable auto-login via kcpassword
-          logg info "Enabling autologin for $USER with acquired sudo password" && sudo enable_autologin "$USER" "$SUDO_PASSWORD"
+          gum log -sl info "Enabling autologin for $USER with acquired sudo password" && sudo enable_autologin "$USER" "$SUDO_PASSWORD"
         fi
 
         ### Reboot
-        logg info 'Reboot required' && exit 140
+        gum log -sl info 'Reboot required' && exit 140
       else
-        logg info 'No reboot required for softwareupdate'
+        gum log -sl info 'No reboot required for softwareupdate'
       fi
     else
-      logg info 'There are no available OS upgrades'
+      gum log -sl info 'There are no available OS upgrades'
     fi
 
     if [ -f "$HOME/.zshrc" ]; then
-      logg info 'Ensuring provision kickstart script is removed from ~/.zshrc'
+      gum log -sl info 'Ensuring provision kickstart script is removed from ~/.zshrc'
       if command -v gsed > /dev/null; then
-        sudo gsed -i '/# TEMPORARY FOR INSTALL DOCTOR MACOS/d' "$HOME/.zshrc" || logg warn "Failed to remove kickstart script from .zshrc"
+        sudo gsed -i '/# TEMPORARY FOR INSTALL DOCTOR MACOS/d' "$HOME/.zshrc" || gum log -sl warn "Failed to remove kickstart script from .zshrc"
       else
-        sudo sed -i '/# TEMPORARY FOR INSTALL DOCTOR MACOS/d' "$HOME/.zshrc" || logg warn "Failed to remove kickstart script from .zshrc"
+        sudo sed -i '/# TEMPORARY FOR INSTALL DOCTOR MACOS/d' "$HOME/.zshrc" || gum log -sl warn "Failed to remove kickstart script from .zshrc"
       fi
     fi
   fi
