Update 22 files
- /home/.chezmoiscripts/_universal/run_onchange_before_11-install-docker.tmpl
- /home/.chezmoiscripts/_universal/run_onchange_before_05-install-homebrew.tmpl
- /home/.chezmoiscripts/_universal/run_onchange_before_10-remove-bloatware.tmpl
- /home/.chezmoiscripts/_universal/run_onchange_before_08-install-zx.tmpl
- /home/.chezmoiscripts/_universal/run_onchange_before_09-ensure-node-version.tmpl
- /home/.chezmoiscripts/universal/run_before_01-decrypt-age-key.tmpl
- /home/.chezmoiscripts/universal/run_onchange_before_11-install-docker.tmpl
- /home/.chezmoiscripts/universal/run_onchange_before_05-install-homebrew.tmpl
- /home/.chezmoiscripts/universal/run_onchange_before_10-remove-bloatware.tmpl
- /home/.chezmoiscripts/universal/run_onchange_before_08-install-zx.tmpl
- /home/.chezmoiscripts/universal/run_onchange_before_09-ensure-node-version.tmpl
- /home/.chezmoiscripts/centos/run_onchange_before_10-install-centos-dependencies.tmpl
- /home/.chezmoiscripts/centos/run_onchange_before_05-upgrade.tmpl
- /home/.chezmoiscripts/fedora/run_onchange_before_10-install-fedora-dependencies.tmpl
- /home/.chezmoitemplates/universal/common-dependencies
- /home/.chezmoitemplates/universal/profile-inline
- /home/.chezmoitemplates/ubuntu/common-dependencies
- /home/.chezmoitemplates/opensuse/common-dependencies
- /home/.chezmoitemplates/freebsd/common-dependencies
- /home/.chezmoitemplates/fedora/common-dependencies
- /home/.chezmoitemplates/debian/common-dependencies
- /home/.chezmoitemplates/archlinux/common-dependencies

diff --git a/home/.chezmoiscripts/universal/run_before_01-decrypt-age-key.tmpl b/home/.chezmoiscripts/universal/run_before_01-decrypt-age-key.tmpl
--- a/home/.chezmoiscripts/universal/run_before_01-decrypt-age-key.tmpl
+++ b/home/.chezmoiscripts/universal/run_before_01-decrypt-age-key.tmpl
@@ -3,19 +3,29 @@
 {{ includeTemplate "universal/logg-before" }}
 {{ includeTemplate "universal/profile-before" }}
 
+### Install Age via Homebrew if not present
+if ! command -v age > /dev/null; then
+  if command -v brew > /dev/null; then
+    brew install age
+  else
+    logg warn '`age` is not installed which is utilized in the decryption process'
+fi
+
 ### Decrypt private key if it is not already present
-if [ ! -f "${XDG_CONFIG_HOME}/age/chezmoi.txt" ]; then
-  mkdir -p "${XDG_CONFIG_HOME}/age"
-  logg star '`PRESS ENTER` if you have not set up your encryption token yet'
-  age --decrypt --output "${XDG_CONFIG_HOME}/age/chezmoi.txt" "{{ .chezmoi.sourceDir }}/key.txt.age" || EXIT_CODE=$?
-  if [ -n "$EXIT_CODE" ]; then
-    logg info 'Proceeding without decrypting age encryption key stored at `~/.local/share/chezmoi/home/key.txt.age`'
-    logg info 'To have Chezmoi handle your encryption (so you can store your private files publicly) take a look at https://shorturl.at/jkpzG'
-    logg info 'Removing all files that begin with encrypted_ because decryption failed'
-    find "$HOME/.local/share/chezmoi" -type f -name "encrypted_*" | while read ENCRYPTED_FILE; do
-      logg info "Removing $ENCRYPTED_FILE"
-      rm -f "$ENCRYPTED_FILE"
-    done
+if command -v age > /dev/null; then
+  if [ ! -f "${XDG_CONFIG_HOME}/age/chezmoi.txt" ]; then
+    mkdir -p "${XDG_CONFIG_HOME}/age"
+    logg star '`PRESS ENTER` if you have not set up your encryption token yet'
+    age --decrypt --output "${XDG_CONFIG_HOME}/age/chezmoi.txt" "{{ .chezmoi.sourceDir }}/key.txt.age" || EXIT_CODE=$?
+    if [ -n "$EXIT_CODE" ]; then
+      logg info 'Proceeding without decrypting age encryption key stored at `~/.local/share/chezmoi/home/key.txt.age`'
+      logg info 'To have Chezmoi handle your encryption (so you can store your private files publicly) take a look at https://shorturl.at/jkpzG'
+      logg info 'Removing all files that begin with encrypted_ because decryption failed'
+      find "$HOME/.local/share/chezmoi" -type f -name "encrypted_*" | while read ENCRYPTED_FILE; do
+        logg info "Removing $ENCRYPTED_FILE"
+        rm -f "$ENCRYPTED_FILE"
+      done
+    fi
   fi
 fi
 
