Update README.md, .local/share/chezmoi/home/dot_local/bin/executable_provision, .local/software.TODO/desktop/Brewfile, .local/software.TODO/desktop/Packages.config, .local/software.TODO/desktop/Wingetfile, .local/software.TODO/development/Brewfile, .local/software.TODO/development/Packages.config, .local/software.TODO/development/Scoopfile, .local/software.TODO/terminal/Brewfile, .local/software.TODO/terminal/Packages.config, .local/software.TODO/terminal/Scoopfile, .local/software.TODO/Gasfile.yml, .local/bin/provision, .local/bin/open, .local/share/chezmoi/home/dot_local/bin/executable_open, .local/share/chezmoi/home/dot_local/Taskfile-local.yml Deleted .local/bin/quickstart, .local/bin/chrome-profile-export, .local/bin/chrome-profile-import, .local/bin/firefox-profile-export, .local/bin/firefox-profile-import, .local/share/chezmoi/home/dot_local/bin/executable_chrome-profile-export, .local/share/chezmoi/home/dot_local/bin/executable_chrome-profile-import, .local/share/chezmoi/home/dot_local/bin/executable_firefox-profile-export, .local/share/chezmoi/home/dot_local/bin/executable_firefox-profile-import, .local/share/chezmoi/home/dot_local/bin/executable_fonttest, .local/share/chezmoi/home/dot_local/bin/executable_quickstart, .local/share/chezmoi/home/dot_local/bin/executable_squash-symlink

diff --git a/.local/share/chezmoi/home/dot_local/Taskfile-local.yml b/.local/share/chezmoi/home/dot_local/Taskfile-local.yml
--- a/.local/share/chezmoi/home/dot_local/Taskfile-local.yml
+++ b/.local/share/chezmoi/home/dot_local/Taskfile-local.yml
@@ -44,6 +44,16 @@ tasks:
     cmds:
       - tar -czpf ~/brave-profile.tar.gz  {{.BrowserProfile}}
 
+  font-test:
+    cmds:
+      - |
+        echo -en "Regular"
+        echo -en "\e[3m Italic \e[0m"
+        echo -en "\e[1m Bold \e[0m"
+        echo -en "\e[3m\e[1m Bold-Italic \e[0m"
+        echo -en " \e[4mUnderline\e[0m "
+        echo -e " \e[9mStrikethrough\e[0m"
+
   provision:
     desc: Provision the environment
     summary: |
@@ -102,3 +112,25 @@ tasks:
       - :install:software:bundle
     cmds:
       - brew bundle --file "$HOME/.local/Brewfile.terminal"
+
+  squash-symlink:
+    summary: |
+      Example: find . -type l -exec /path/tos/script {} +
+    cmds:
+      - |
+        set -e
+        for link; do
+            test -h "$link" || continue
+            dir=$(dirname "$link")
+            reltarget=$(readlink "$link")
+            case $reltarget in
+                /*) abstarget=$reltarget;;
+                *)  abstarget=$dir/$reltarget;;
+            esac
+            rm -fv "$link"
+            cp -afv "$abstarget" "$link" || {
+                # on failure, restore the symlink
+                rm -rfv "$link"
+                ln -sfv "$reltarget" "$link"
+            }
+        done
